---
driver:
  name: vagrant

## The forwarded_port port feature lets you connect to ports on the VM guest via
## localhost on the host.
## see also: https://www.vagrantup.com/docs/networking/forwarded_ports.html

#  network:
#    - ["forwarded_port", {guest: 80, host: 8080}]

provisioner:
  name: chef_solo
  product_name: chef
  product_version: 15

verifier:
  name: inspec

platforms:
  - name: centos-7

suites:
  - name: default
    run_list: recipe[tgw_wordpress::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
  - name: database
    run_list: recipe[tgw_wordpress::database]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
